### ISSUE TITLE
System.InvalidOperationException: UnderlyingCredential is not an OIDC token provider

### ISSUE THREAD

**Issue by jjdelorme** [jjdelorme/cloudrungrpc#1]
Not sure what has changed, but I'm not unable to run the client app connecting to Cloud Run.  Using the following command:

```dotnet run https://mygrpc-62b5pp6dlq-uc.a.run.app Jason```

...throws this exception:

```bash
Unhandled exception. System.InvalidOperationException: UnderlyingCredential is not an OIDC token provider. Only ServiceAccountCredential, ComputeCredential are supported OIDC token providers.
   at Google.Apis.Auth.OAuth2.GoogleCredential.GetOidcTokenAsync(OidcTokenOptions options, CancellationToken cancellationToken)
   at CloudRunGrpc.Client.Program.GetTokenAsync(String serverAddress) in /home/jason/dev/grpc/client/Program.cs:line 60
   at CloudRunGrpc.Client.Program.CreateChannelAsync(String address) in /home/jason/dev/grpc/client/Program.cs:line 37
   at CloudRunGrpc.Client.Program.Main(String[] args) in /home/jason/dev/grpc/client/Program.cs:line 22
   at CloudRunGrpc.Client.Program.<Main>(String[] args)
```

**Comment by jjdelorme** [comment]
RESOLVED! Issue was an expired service account (expired at end of year).  Downloaded a new service account key and set the appropriate env variable: ```export GOOGLE_APPLICATION_CREDENTIALS=~/dev/grpc/google-key.json```
